//
// DO NOT EDIT.
//
// Generated by the protocol buffer compiler.
// Source: appointment.proto
//

//
// Copyright 2018, gRPC Authors All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
import GRPC
import NIO
import SwiftProtobuf


/// Usage: instantiate `Nambadoctor_V1_AppointmentWorkerV1Client`, then call methods of this protocol to make API calls.
internal protocol Nambadoctor_V1_AppointmentWorkerV1ClientProtocol: GRPCClient {
  var serviceName: String { get }
  var interceptors: Nambadoctor_V1_AppointmentWorkerV1ClientInterceptorFactoryProtocol? { get }

  func upsertNewAppointment(
    _ request: Nambadoctor_V1_AppointmentObject,
    callOptions: CallOptions?
  ) -> UnaryCall<Nambadoctor_V1_AppointmentObject, Nambadoctor_V1_AppointmentRequest>

  func getAllPatientAppointments(
    _ request: Nambadoctor_V1_AppointmentPatientRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Nambadoctor_V1_AppointmentPatientRequest, Nambadoctor_V1_BulkAppointmentsResponse>

  func getAllDoctorAppointments(
    _ request: Nambadoctor_V1_AppointmentDoctorRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Nambadoctor_V1_AppointmentDoctorRequest, Nambadoctor_V1_BulkAppointmentsResponse>

  func getUniqueAppointment(
    _ request: Nambadoctor_V1_AppointmentRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Nambadoctor_V1_AppointmentRequest, Nambadoctor_V1_AppointmentObject>
}

extension Nambadoctor_V1_AppointmentWorkerV1ClientProtocol {
  internal var serviceName: String {
    return "nambadoctor.v1.AppointmentWorkerV1"
  }

  /// Unary call to UpsertNewAppointment
  ///
  /// - Parameters:
  ///   - request: Request to send to UpsertNewAppointment.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  internal func upsertNewAppointment(
    _ request: Nambadoctor_V1_AppointmentObject,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Nambadoctor_V1_AppointmentObject, Nambadoctor_V1_AppointmentRequest> {
    return self.makeUnaryCall(
      path: "/nambadoctor.v1.AppointmentWorkerV1/UpsertNewAppointment",
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeUpsertNewAppointmentInterceptors() ?? []
    )
  }

  /// Unary call to GetAllPatientAppointments
  ///
  /// - Parameters:
  ///   - request: Request to send to GetAllPatientAppointments.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  internal func getAllPatientAppointments(
    _ request: Nambadoctor_V1_AppointmentPatientRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Nambadoctor_V1_AppointmentPatientRequest, Nambadoctor_V1_BulkAppointmentsResponse> {
    return self.makeUnaryCall(
      path: "/nambadoctor.v1.AppointmentWorkerV1/GetAllPatientAppointments",
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeGetAllPatientAppointmentsInterceptors() ?? []
    )
  }

  /// Unary call to GetAllDoctorAppointments
  ///
  /// - Parameters:
  ///   - request: Request to send to GetAllDoctorAppointments.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  internal func getAllDoctorAppointments(
    _ request: Nambadoctor_V1_AppointmentDoctorRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Nambadoctor_V1_AppointmentDoctorRequest, Nambadoctor_V1_BulkAppointmentsResponse> {
    return self.makeUnaryCall(
      path: "/nambadoctor.v1.AppointmentWorkerV1/GetAllDoctorAppointments",
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeGetAllDoctorAppointmentsInterceptors() ?? []
    )
  }

  /// Unary call to GetUniqueAppointment
  ///
  /// - Parameters:
  ///   - request: Request to send to GetUniqueAppointment.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  internal func getUniqueAppointment(
    _ request: Nambadoctor_V1_AppointmentRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Nambadoctor_V1_AppointmentRequest, Nambadoctor_V1_AppointmentObject> {
    return self.makeUnaryCall(
      path: "/nambadoctor.v1.AppointmentWorkerV1/GetUniqueAppointment",
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeGetUniqueAppointmentInterceptors() ?? []
    )
  }
}

internal protocol Nambadoctor_V1_AppointmentWorkerV1ClientInterceptorFactoryProtocol {

  /// - Returns: Interceptors to use when invoking 'upsertNewAppointment'.
  func makeUpsertNewAppointmentInterceptors() -> [ClientInterceptor<Nambadoctor_V1_AppointmentObject, Nambadoctor_V1_AppointmentRequest>]

  /// - Returns: Interceptors to use when invoking 'getAllPatientAppointments'.
  func makeGetAllPatientAppointmentsInterceptors() -> [ClientInterceptor<Nambadoctor_V1_AppointmentPatientRequest, Nambadoctor_V1_BulkAppointmentsResponse>]

  /// - Returns: Interceptors to use when invoking 'getAllDoctorAppointments'.
  func makeGetAllDoctorAppointmentsInterceptors() -> [ClientInterceptor<Nambadoctor_V1_AppointmentDoctorRequest, Nambadoctor_V1_BulkAppointmentsResponse>]

  /// - Returns: Interceptors to use when invoking 'getUniqueAppointment'.
  func makeGetUniqueAppointmentInterceptors() -> [ClientInterceptor<Nambadoctor_V1_AppointmentRequest, Nambadoctor_V1_AppointmentObject>]
}

internal final class Nambadoctor_V1_AppointmentWorkerV1Client: Nambadoctor_V1_AppointmentWorkerV1ClientProtocol {
  internal let channel: GRPCChannel
  internal var defaultCallOptions: CallOptions
  internal var interceptors: Nambadoctor_V1_AppointmentWorkerV1ClientInterceptorFactoryProtocol?

  /// Creates a client for the nambadoctor.v1.AppointmentWorkerV1 service.
  ///
  /// - Parameters:
  ///   - channel: `GRPCChannel` to the service host.
  ///   - defaultCallOptions: Options to use for each service call if the user doesn't provide them.
  ///   - interceptors: A factory providing interceptors for each RPC.
  internal init(
    channel: GRPCChannel,
    defaultCallOptions: CallOptions = CallOptions(),
    interceptors: Nambadoctor_V1_AppointmentWorkerV1ClientInterceptorFactoryProtocol? = nil
  ) {
    self.channel = channel
    self.defaultCallOptions = defaultCallOptions
    self.interceptors = interceptors
  }
}

/// To build a server, implement a class that conforms to this protocol.
internal protocol Nambadoctor_V1_AppointmentWorkerV1Provider: CallHandlerProvider {
  var interceptors: Nambadoctor_V1_AppointmentWorkerV1ServerInterceptorFactoryProtocol? { get }

  func upsertNewAppointment(request: Nambadoctor_V1_AppointmentObject, context: StatusOnlyCallContext) -> EventLoopFuture<Nambadoctor_V1_AppointmentRequest>

  func getAllPatientAppointments(request: Nambadoctor_V1_AppointmentPatientRequest, context: StatusOnlyCallContext) -> EventLoopFuture<Nambadoctor_V1_BulkAppointmentsResponse>

  func getAllDoctorAppointments(request: Nambadoctor_V1_AppointmentDoctorRequest, context: StatusOnlyCallContext) -> EventLoopFuture<Nambadoctor_V1_BulkAppointmentsResponse>

  func getUniqueAppointment(request: Nambadoctor_V1_AppointmentRequest, context: StatusOnlyCallContext) -> EventLoopFuture<Nambadoctor_V1_AppointmentObject>
}

extension Nambadoctor_V1_AppointmentWorkerV1Provider {
  internal var serviceName: Substring { return "nambadoctor.v1.AppointmentWorkerV1" }

  /// Determines, calls and returns the appropriate request handler, depending on the request's method.
  /// Returns nil for methods not handled by this service.
  internal func handle(
    method name: Substring,
    context: CallHandlerContext
  ) -> GRPCServerHandlerProtocol? {
    switch name {
    case "UpsertNewAppointment":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Nambadoctor_V1_AppointmentObject>(),
        responseSerializer: ProtobufSerializer<Nambadoctor_V1_AppointmentRequest>(),
        interceptors: self.interceptors?.makeUpsertNewAppointmentInterceptors() ?? [],
        userFunction: self.upsertNewAppointment(request:context:)
      )

    case "GetAllPatientAppointments":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Nambadoctor_V1_AppointmentPatientRequest>(),
        responseSerializer: ProtobufSerializer<Nambadoctor_V1_BulkAppointmentsResponse>(),
        interceptors: self.interceptors?.makeGetAllPatientAppointmentsInterceptors() ?? [],
        userFunction: self.getAllPatientAppointments(request:context:)
      )

    case "GetAllDoctorAppointments":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Nambadoctor_V1_AppointmentDoctorRequest>(),
        responseSerializer: ProtobufSerializer<Nambadoctor_V1_BulkAppointmentsResponse>(),
        interceptors: self.interceptors?.makeGetAllDoctorAppointmentsInterceptors() ?? [],
        userFunction: self.getAllDoctorAppointments(request:context:)
      )

    case "GetUniqueAppointment":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Nambadoctor_V1_AppointmentRequest>(),
        responseSerializer: ProtobufSerializer<Nambadoctor_V1_AppointmentObject>(),
        interceptors: self.interceptors?.makeGetUniqueAppointmentInterceptors() ?? [],
        userFunction: self.getUniqueAppointment(request:context:)
      )

    default:
      return nil
    }
  }
}

internal protocol Nambadoctor_V1_AppointmentWorkerV1ServerInterceptorFactoryProtocol {

  /// - Returns: Interceptors to use when handling 'upsertNewAppointment'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeUpsertNewAppointmentInterceptors() -> [ServerInterceptor<Nambadoctor_V1_AppointmentObject, Nambadoctor_V1_AppointmentRequest>]

  /// - Returns: Interceptors to use when handling 'getAllPatientAppointments'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeGetAllPatientAppointmentsInterceptors() -> [ServerInterceptor<Nambadoctor_V1_AppointmentPatientRequest, Nambadoctor_V1_BulkAppointmentsResponse>]

  /// - Returns: Interceptors to use when handling 'getAllDoctorAppointments'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeGetAllDoctorAppointmentsInterceptors() -> [ServerInterceptor<Nambadoctor_V1_AppointmentDoctorRequest, Nambadoctor_V1_BulkAppointmentsResponse>]

  /// - Returns: Interceptors to use when handling 'getUniqueAppointment'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeGetUniqueAppointmentInterceptors() -> [ServerInterceptor<Nambadoctor_V1_AppointmentRequest, Nambadoctor_V1_AppointmentObject>]
}
