//
// DO NOT EDIT.
//
// Generated by the protocol buffer compiler.
// Source: logon.proto
//

//
// Copyright 2018, gRPC Authors All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
import GRPC
import NIO
import SwiftProtobuf


/// Usage: instantiate `Nambadoctor_V1_LogonWorkerV1Client`, then call methods of this protocol to make API calls.
internal protocol Nambadoctor_V1_LogonWorkerV1ClientProtocol: GRPCClient {
  var serviceName: String { get }
  var interceptors: Nambadoctor_V1_LogonWorkerV1ClientInterceptorFactoryProtocol? { get }

  func saveDevice(
    _ request: Nambadoctor_V1_DeviceMessage,
    callOptions: CallOptions?
  ) -> UnaryCall<Nambadoctor_V1_DeviceMessage, Nambadoctor_V1_ObjectResponseMessage>

  func logon(
    _ request: Nambadoctor_V1_LogonRequestMessage,
    callOptions: CallOptions?
  ) -> UnaryCall<Nambadoctor_V1_LogonRequestMessage, Nambadoctor_V1_LogonResponseMessage>

  func getUserType(
    _ request: Nambadoctor_V1_LogonRequestUserType,
    callOptions: CallOptions?
  ) -> UnaryCall<Nambadoctor_V1_LogonRequestUserType, Nambadoctor_V1_LogonResponseUserType>
}

extension Nambadoctor_V1_LogonWorkerV1ClientProtocol {
  internal var serviceName: String {
    return "nambadoctor.v1.LogonWorkerV1"
  }

  /// Unary call to SaveDevice
  ///
  /// - Parameters:
  ///   - request: Request to send to SaveDevice.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  internal func saveDevice(
    _ request: Nambadoctor_V1_DeviceMessage,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Nambadoctor_V1_DeviceMessage, Nambadoctor_V1_ObjectResponseMessage> {
    return self.makeUnaryCall(
      path: "/nambadoctor.v1.LogonWorkerV1/SaveDevice",
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeSaveDeviceInterceptors() ?? []
    )
  }

  /// Unary call to Logon
  ///
  /// - Parameters:
  ///   - request: Request to send to Logon.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  internal func logon(
    _ request: Nambadoctor_V1_LogonRequestMessage,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Nambadoctor_V1_LogonRequestMessage, Nambadoctor_V1_LogonResponseMessage> {
    return self.makeUnaryCall(
      path: "/nambadoctor.v1.LogonWorkerV1/Logon",
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeLogonInterceptors() ?? []
    )
  }

  /// Unary call to GetUserType
  ///
  /// - Parameters:
  ///   - request: Request to send to GetUserType.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  internal func getUserType(
    _ request: Nambadoctor_V1_LogonRequestUserType,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Nambadoctor_V1_LogonRequestUserType, Nambadoctor_V1_LogonResponseUserType> {
    return self.makeUnaryCall(
      path: "/nambadoctor.v1.LogonWorkerV1/GetUserType",
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeGetUserTypeInterceptors() ?? []
    )
  }
}

internal protocol Nambadoctor_V1_LogonWorkerV1ClientInterceptorFactoryProtocol {

  /// - Returns: Interceptors to use when invoking 'saveDevice'.
  func makeSaveDeviceInterceptors() -> [ClientInterceptor<Nambadoctor_V1_DeviceMessage, Nambadoctor_V1_ObjectResponseMessage>]

  /// - Returns: Interceptors to use when invoking 'logon'.
  func makeLogonInterceptors() -> [ClientInterceptor<Nambadoctor_V1_LogonRequestMessage, Nambadoctor_V1_LogonResponseMessage>]

  /// - Returns: Interceptors to use when invoking 'getUserType'.
  func makeGetUserTypeInterceptors() -> [ClientInterceptor<Nambadoctor_V1_LogonRequestUserType, Nambadoctor_V1_LogonResponseUserType>]
}

internal final class Nambadoctor_V1_LogonWorkerV1Client: Nambadoctor_V1_LogonWorkerV1ClientProtocol {
  internal let channel: GRPCChannel
  internal var defaultCallOptions: CallOptions
  internal var interceptors: Nambadoctor_V1_LogonWorkerV1ClientInterceptorFactoryProtocol?

  /// Creates a client for the nambadoctor.v1.LogonWorkerV1 service.
  ///
  /// - Parameters:
  ///   - channel: `GRPCChannel` to the service host.
  ///   - defaultCallOptions: Options to use for each service call if the user doesn't provide them.
  ///   - interceptors: A factory providing interceptors for each RPC.
  internal init(
    channel: GRPCChannel,
    defaultCallOptions: CallOptions = CallOptions(),
    interceptors: Nambadoctor_V1_LogonWorkerV1ClientInterceptorFactoryProtocol? = nil
  ) {
    self.channel = channel
    self.defaultCallOptions = defaultCallOptions
    self.interceptors = interceptors
  }
}

/// To build a server, implement a class that conforms to this protocol.
internal protocol Nambadoctor_V1_LogonWorkerV1Provider: CallHandlerProvider {
  var interceptors: Nambadoctor_V1_LogonWorkerV1ServerInterceptorFactoryProtocol? { get }

  func saveDevice(request: Nambadoctor_V1_DeviceMessage, context: StatusOnlyCallContext) -> EventLoopFuture<Nambadoctor_V1_ObjectResponseMessage>

  func logon(request: Nambadoctor_V1_LogonRequestMessage, context: StatusOnlyCallContext) -> EventLoopFuture<Nambadoctor_V1_LogonResponseMessage>

  func getUserType(request: Nambadoctor_V1_LogonRequestUserType, context: StatusOnlyCallContext) -> EventLoopFuture<Nambadoctor_V1_LogonResponseUserType>
}

extension Nambadoctor_V1_LogonWorkerV1Provider {
  internal var serviceName: Substring { return "nambadoctor.v1.LogonWorkerV1" }

  /// Determines, calls and returns the appropriate request handler, depending on the request's method.
  /// Returns nil for methods not handled by this service.
  internal func handle(
    method name: Substring,
    context: CallHandlerContext
  ) -> GRPCServerHandlerProtocol? {
    switch name {
    case "SaveDevice":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Nambadoctor_V1_DeviceMessage>(),
        responseSerializer: ProtobufSerializer<Nambadoctor_V1_ObjectResponseMessage>(),
        interceptors: self.interceptors?.makeSaveDeviceInterceptors() ?? [],
        userFunction: self.saveDevice(request:context:)
      )

    case "Logon":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Nambadoctor_V1_LogonRequestMessage>(),
        responseSerializer: ProtobufSerializer<Nambadoctor_V1_LogonResponseMessage>(),
        interceptors: self.interceptors?.makeLogonInterceptors() ?? [],
        userFunction: self.logon(request:context:)
      )

    case "GetUserType":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Nambadoctor_V1_LogonRequestUserType>(),
        responseSerializer: ProtobufSerializer<Nambadoctor_V1_LogonResponseUserType>(),
        interceptors: self.interceptors?.makeGetUserTypeInterceptors() ?? [],
        userFunction: self.getUserType(request:context:)
      )

    default:
      return nil
    }
  }
}

internal protocol Nambadoctor_V1_LogonWorkerV1ServerInterceptorFactoryProtocol {

  /// - Returns: Interceptors to use when handling 'saveDevice'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeSaveDeviceInterceptors() -> [ServerInterceptor<Nambadoctor_V1_DeviceMessage, Nambadoctor_V1_ObjectResponseMessage>]

  /// - Returns: Interceptors to use when handling 'logon'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeLogonInterceptors() -> [ServerInterceptor<Nambadoctor_V1_LogonRequestMessage, Nambadoctor_V1_LogonResponseMessage>]

  /// - Returns: Interceptors to use when handling 'getUserType'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeGetUserTypeInterceptors() -> [ServerInterceptor<Nambadoctor_V1_LogonRequestUserType, Nambadoctor_V1_LogonResponseUserType>]
}
