//
// DO NOT EDIT.
//
// Generated by the protocol buffer compiler.
// Source: notification.proto
//

//
// Copyright 2018, gRPC Authors All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
import GRPC
import NIO
import SwiftProtobuf


/// Usage: instantiate `Nambadoctor_V1_NotificationWorkerV1Client`, then call methods of this protocol to make API calls.
internal protocol Nambadoctor_V1_NotificationWorkerV1ClientProtocol: GRPCClient {
  var serviceName: String { get }
  var interceptors: Nambadoctor_V1_NotificationWorkerV1ClientInterceptorFactoryProtocol? { get }

  func sendNotification(
    _ request: Nambadoctor_V1_NotificationRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Nambadoctor_V1_NotificationRequest, Nambadoctor_V1_NotificationResponse>
}

extension Nambadoctor_V1_NotificationWorkerV1ClientProtocol {
  internal var serviceName: String {
    return "nambadoctor.v1.NotificationWorkerV1"
  }

  /// Unary call to SendNotification
  ///
  /// - Parameters:
  ///   - request: Request to send to SendNotification.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  internal func sendNotification(
    _ request: Nambadoctor_V1_NotificationRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Nambadoctor_V1_NotificationRequest, Nambadoctor_V1_NotificationResponse> {
    return self.makeUnaryCall(
      path: "/nambadoctor.v1.NotificationWorkerV1/SendNotification",
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeSendNotificationInterceptors() ?? []
    )
  }
}

internal protocol Nambadoctor_V1_NotificationWorkerV1ClientInterceptorFactoryProtocol {

  /// - Returns: Interceptors to use when invoking 'sendNotification'.
  func makeSendNotificationInterceptors() -> [ClientInterceptor<Nambadoctor_V1_NotificationRequest, Nambadoctor_V1_NotificationResponse>]
}

internal final class Nambadoctor_V1_NotificationWorkerV1Client: Nambadoctor_V1_NotificationWorkerV1ClientProtocol {
  internal let channel: GRPCChannel
  internal var defaultCallOptions: CallOptions
  internal var interceptors: Nambadoctor_V1_NotificationWorkerV1ClientInterceptorFactoryProtocol?

  /// Creates a client for the nambadoctor.v1.NotificationWorkerV1 service.
  ///
  /// - Parameters:
  ///   - channel: `GRPCChannel` to the service host.
  ///   - defaultCallOptions: Options to use for each service call if the user doesn't provide them.
  ///   - interceptors: A factory providing interceptors for each RPC.
  internal init(
    channel: GRPCChannel,
    defaultCallOptions: CallOptions = CallOptions(),
    interceptors: Nambadoctor_V1_NotificationWorkerV1ClientInterceptorFactoryProtocol? = nil
  ) {
    self.channel = channel
    self.defaultCallOptions = defaultCallOptions
    self.interceptors = interceptors
  }
}

/// To build a server, implement a class that conforms to this protocol.
internal protocol Nambadoctor_V1_NotificationWorkerV1Provider: CallHandlerProvider {
  var interceptors: Nambadoctor_V1_NotificationWorkerV1ServerInterceptorFactoryProtocol? { get }

  func sendNotification(request: Nambadoctor_V1_NotificationRequest, context: StatusOnlyCallContext) -> EventLoopFuture<Nambadoctor_V1_NotificationResponse>
}

extension Nambadoctor_V1_NotificationWorkerV1Provider {
  internal var serviceName: Substring { return "nambadoctor.v1.NotificationWorkerV1" }

  /// Determines, calls and returns the appropriate request handler, depending on the request's method.
  /// Returns nil for methods not handled by this service.
  internal func handle(
    method name: Substring,
    context: CallHandlerContext
  ) -> GRPCServerHandlerProtocol? {
    switch name {
    case "SendNotification":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Nambadoctor_V1_NotificationRequest>(),
        responseSerializer: ProtobufSerializer<Nambadoctor_V1_NotificationResponse>(),
        interceptors: self.interceptors?.makeSendNotificationInterceptors() ?? [],
        userFunction: self.sendNotification(request:context:)
      )

    default:
      return nil
    }
  }
}

internal protocol Nambadoctor_V1_NotificationWorkerV1ServerInterceptorFactoryProtocol {

  /// - Returns: Interceptors to use when handling 'sendNotification'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeSendNotificationInterceptors() -> [ServerInterceptor<Nambadoctor_V1_NotificationRequest, Nambadoctor_V1_NotificationResponse>]
}
