//
// DO NOT EDIT.
//
// Generated by the protocol buffer compiler.
// Source: prescription.proto
//

//
// Copyright 2018, gRPC Authors All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
import GRPC
import NIO
import SwiftProtobuf


/// Usage: instantiate `Nambadoctor_V1_PrescriptionWorkerV1Client`, then call methods of this protocol to make API calls.
internal protocol Nambadoctor_V1_PrescriptionWorkerV1ClientProtocol: GRPCClient {
  var serviceName: String { get }
  var interceptors: Nambadoctor_V1_PrescriptionWorkerV1ClientInterceptorFactoryProtocol? { get }

  func saveNewPrescription(
    _ request: Nambadoctor_V1_PrescriptionObject,
    callOptions: CallOptions?
  ) -> UnaryCall<Nambadoctor_V1_PrescriptionObject, Nambadoctor_V1_PrescriptionResponse>

  func getPrescriptionOfAppointment(
    _ request: Nambadoctor_V1_PrescriptionRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Nambadoctor_V1_PrescriptionRequest, Nambadoctor_V1_PrescriptionObject>
}

extension Nambadoctor_V1_PrescriptionWorkerV1ClientProtocol {
  internal var serviceName: String {
    return "nambadoctor.v1.PrescriptionWorkerV1"
  }

  /// Unary call to SaveNewPrescription
  ///
  /// - Parameters:
  ///   - request: Request to send to SaveNewPrescription.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  internal func saveNewPrescription(
    _ request: Nambadoctor_V1_PrescriptionObject,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Nambadoctor_V1_PrescriptionObject, Nambadoctor_V1_PrescriptionResponse> {
    return self.makeUnaryCall(
      path: "/nambadoctor.v1.PrescriptionWorkerV1/SaveNewPrescription",
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeSaveNewPrescriptionInterceptors() ?? []
    )
  }

  /// Unary call to GetPrescriptionOfAppointment
  ///
  /// - Parameters:
  ///   - request: Request to send to GetPrescriptionOfAppointment.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  internal func getPrescriptionOfAppointment(
    _ request: Nambadoctor_V1_PrescriptionRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Nambadoctor_V1_PrescriptionRequest, Nambadoctor_V1_PrescriptionObject> {
    return self.makeUnaryCall(
      path: "/nambadoctor.v1.PrescriptionWorkerV1/GetPrescriptionOfAppointment",
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeGetPrescriptionOfAppointmentInterceptors() ?? []
    )
  }
}

internal protocol Nambadoctor_V1_PrescriptionWorkerV1ClientInterceptorFactoryProtocol {

  /// - Returns: Interceptors to use when invoking 'saveNewPrescription'.
  func makeSaveNewPrescriptionInterceptors() -> [ClientInterceptor<Nambadoctor_V1_PrescriptionObject, Nambadoctor_V1_PrescriptionResponse>]

  /// - Returns: Interceptors to use when invoking 'getPrescriptionOfAppointment'.
  func makeGetPrescriptionOfAppointmentInterceptors() -> [ClientInterceptor<Nambadoctor_V1_PrescriptionRequest, Nambadoctor_V1_PrescriptionObject>]
}

internal final class Nambadoctor_V1_PrescriptionWorkerV1Client: Nambadoctor_V1_PrescriptionWorkerV1ClientProtocol {
  internal let channel: GRPCChannel
  internal var defaultCallOptions: CallOptions
  internal var interceptors: Nambadoctor_V1_PrescriptionWorkerV1ClientInterceptorFactoryProtocol?

  /// Creates a client for the nambadoctor.v1.PrescriptionWorkerV1 service.
  ///
  /// - Parameters:
  ///   - channel: `GRPCChannel` to the service host.
  ///   - defaultCallOptions: Options to use for each service call if the user doesn't provide them.
  ///   - interceptors: A factory providing interceptors for each RPC.
  internal init(
    channel: GRPCChannel,
    defaultCallOptions: CallOptions = CallOptions(),
    interceptors: Nambadoctor_V1_PrescriptionWorkerV1ClientInterceptorFactoryProtocol? = nil
  ) {
    self.channel = channel
    self.defaultCallOptions = defaultCallOptions
    self.interceptors = interceptors
  }
}

/// To build a server, implement a class that conforms to this protocol.
internal protocol Nambadoctor_V1_PrescriptionWorkerV1Provider: CallHandlerProvider {
  var interceptors: Nambadoctor_V1_PrescriptionWorkerV1ServerInterceptorFactoryProtocol? { get }

  func saveNewPrescription(request: Nambadoctor_V1_PrescriptionObject, context: StatusOnlyCallContext) -> EventLoopFuture<Nambadoctor_V1_PrescriptionResponse>

  func getPrescriptionOfAppointment(request: Nambadoctor_V1_PrescriptionRequest, context: StatusOnlyCallContext) -> EventLoopFuture<Nambadoctor_V1_PrescriptionObject>
}

extension Nambadoctor_V1_PrescriptionWorkerV1Provider {
  internal var serviceName: Substring { return "nambadoctor.v1.PrescriptionWorkerV1" }

  /// Determines, calls and returns the appropriate request handler, depending on the request's method.
  /// Returns nil for methods not handled by this service.
  internal func handle(
    method name: Substring,
    context: CallHandlerContext
  ) -> GRPCServerHandlerProtocol? {
    switch name {
    case "SaveNewPrescription":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Nambadoctor_V1_PrescriptionObject>(),
        responseSerializer: ProtobufSerializer<Nambadoctor_V1_PrescriptionResponse>(),
        interceptors: self.interceptors?.makeSaveNewPrescriptionInterceptors() ?? [],
        userFunction: self.saveNewPrescription(request:context:)
      )

    case "GetPrescriptionOfAppointment":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<Nambadoctor_V1_PrescriptionRequest>(),
        responseSerializer: ProtobufSerializer<Nambadoctor_V1_PrescriptionObject>(),
        interceptors: self.interceptors?.makeGetPrescriptionOfAppointmentInterceptors() ?? [],
        userFunction: self.getPrescriptionOfAppointment(request:context:)
      )

    default:
      return nil
    }
  }
}

internal protocol Nambadoctor_V1_PrescriptionWorkerV1ServerInterceptorFactoryProtocol {

  /// - Returns: Interceptors to use when handling 'saveNewPrescription'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeSaveNewPrescriptionInterceptors() -> [ServerInterceptor<Nambadoctor_V1_PrescriptionObject, Nambadoctor_V1_PrescriptionResponse>]

  /// - Returns: Interceptors to use when handling 'getPrescriptionOfAppointment'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeGetPrescriptionOfAppointmentInterceptors() -> [ServerInterceptor<Nambadoctor_V1_PrescriptionRequest, Nambadoctor_V1_PrescriptionObject>]
}
